name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Login à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build de l’image Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:latest ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:${{ github.sha }}

      - name: Push de l’image sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:${{ github.sha }}
