name: Build & Push Docker Image

on:
  workflow_run:
    workflows: ["CI Tests"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Télécharger l’artefact de test
        uses: actions/download-artifact@v3
        with:
          name: test-success

      - name: Vérifier si les tests ont réussi
        run: |
          if [ ! -f test_success.txt ]; then
            echo "Les tests n'ont pas réussi, arrêt du build."
            exit 1
          fi

      - name: Login à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Déterminer le tag de l'image
        id: docker_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build de l’image Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:latest ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:${{ env.TAG }}

      - name: Push de l’image sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cartel-cocktail:${{ env.TAG }}
